name: lecturer_info
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  drift: ^2.8.2
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  form_builder_validators: ^9.0.0
  fpdart: ^0.6.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  mockito: ^5.4.2
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  sqflite: ^2.2.8+4
  sqlite3_flutter_libs: ^0.5.15
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  drift_dev: ^2.8.3
  test: ^1.24.1
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
